# Generated by Django 5.2.1 on 2025-05-21 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='capitulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruta_contenido', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='colorProgreso',
            fields=[
                ('progreso', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('color', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruta_modulo', models.CharField(max_length=200)),
                ('id_capitulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysapp.capitulo')),
            ],
        ),
        migrations.CreateModel(
            name='ProgresoCapitulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_capitulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysapp.capitulo')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('progreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysapp.colorprogreso')),
            ],
            options={
                'unique_together': {('id_usuario', 'id_capitulo')},
            },
        ),
        migrations.CreateModel(
            name='resulatadoPrueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.PositiveIntegerField()),
                ('id_modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysapp.modulo')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('id_usuario', 'id_modulo')},
            },
        ),
    ]
