# Generated by Django 5.2.1 on 2025-05-21 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='hola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.CharField(max_length=200)),
            ],
        ),
    ]
