# Generated by Django 5.2.1 on 2025-05-22 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysapp', '0003_delete_hola'),
    ]

    operations = [
        migrations.AddField(
            model_name='capitulo',
            name='orden',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modulo',
            name='orden',
            field=models.PositiveIntegerField(default=None),
            preserve_default=False,
        ),
    ]
